export const VIABILITY_PARAMETERS_REPOSITORY_TOKEN = Symbol(
  'VIABILITY_PARAMETERS_REPOSITORY_TOKEN',
);
export const VIABILITY_AUCTION_STATS_PORT_TOKEN = Symbol(
  'VIABILITY_AUCTION_STATS_PORT_TOKEN',
);
export const VIABILITY_OFFER_QUERY_PORT_TOKEN = Symbol(
  'VIABILITY_OFFER_QUERY_PORT_TOKEN',
);
