export const LINE_FOUNDATIONS_QUERY_PORT_TOKEN = Symbol(
  'LINE_FOUNDATIONS_QUERY_PORT_TOKEN',
);

export const FOUNDATION_VOLUME_MATRICES_QUERY_PORT_TOKEN = Symbol(
  'FOUNDATION_VOLUME_MATRICES_QUERY_PORT_TOKEN',
);
