export const BASELINES_REPOSITORY_TOKEN = Symbol('BASELINES_REPOSITORY_TOKEN');

export const CHANGE_ORDERS_REPOSITORY_TOKEN = Symbol(
  'CHANGE_ORDERS_REPOSITORY_TOKEN',
);

export const PROGRESS_RECORDS_REPOSITORY_TOKEN = Symbol(
  'PROGRESS_RECORDS_REPOSITORY_TOKEN',
);

export const BASELINE_OFFER_QUERY_PORT_TOKEN = Symbol(
  'BASELINE_OFFER_QUERY_PORT_TOKEN',
);

export const AUDIT_TRAIL_PORT_TOKEN = Symbol('AUDIT_TRAIL_PORT_TOKEN');

export const ERP_SPREADSHEET_PORT_TOKEN = Symbol('ERP_SPREADSHEET_PORT_TOKEN');
