export const STAKING_TOWERS_REPOSITORY_TOKEN = Symbol(
  'STAKING_TOWERS_REPOSITORY_TOKEN',
);

export const PRELIMINARY_DISTRIBUTION_REPOSITORY_TOKEN = Symbol(
  'PRELIMINARY_DISTRIBUTION_REPOSITORY_TOKEN',
);

export const STAKING_CATALOG_QUERY_PORT_TOKEN = Symbol(
  'STAKING_CATALOG_QUERY_PORT_TOKEN',
);

export const STAKING_UNIT_OF_WORK_TOKEN = Symbol('STAKING_UNIT_OF_WORK_TOKEN');
