export const ANEEL_AUCTION_RESULTS_PORT_TOKEN = Symbol(
  'ANEEL_AUCTION_RESULTS_PORT_TOKEN',
);
export const AUCTION_HISTORY_REPOSITORY_TOKEN = Symbol(
  'AUCTION_HISTORY_REPOSITORY_TOKEN',
);
export const AUCTION_HISTORY_AUDIT_TRAIL_PORT_TOKEN = Symbol(
  'AUCTION_HISTORY_AUDIT_TRAIL_PORT_TOKEN',
);
