export const LINE_ELECTROMECHANICAL_QUERY_PORT_TOKEN = Symbol(
  'LINE_ELECTROMECHANICAL_QUERY_PORT_TOKEN',
);

export const ELECTROMECHANICAL_CATALOGS_QUERY_PORT_TOKEN = Symbol(
  'ELECTROMECHANICAL_CATALOGS_QUERY_PORT_TOKEN',
);
